FROM ubuntu AS build
RUN apt-get update
RUN apt-get --assume-yes  install curl
RUN mkdir maweb
WORKDIR maweb
RUN curl https://circabc.europa.eu/sd/a/5a995965-b3dd-4173-9161-d1dee6275960/MappingAssistantWebApp_JAVA_v8_2021-10-07.zip --output maweb.zip
RUN apt-get install unzip
RUN unzip maweb.zip

FROM tomcat:9-jre8-openjdk
COPY conf/fake-certificate-cert.pem /usr/local/tomcat/ssl/fake-certificate-cert.pem
COPY conf/fake-certificate-key.pem /usr/local/tomcat/ssl/fake-certificate-key.pem
COPY conf/server.xml /usr/local/tomcat/conf/server.xml
COPY --from=build maweb/app/maws.war /usr/local/tomcat/webapps/ROOT.war
COPY --from=build maweb/app/classpath /usr/local/tomcat/classpath
COPY --from=build maweb/app/libs/bcprov-jdk15on-1.68.jar /usr/local/tomcat/lib
RUN echo "# Add classpath to Tomcat CLASSPATH" > /usr/local/tomcat/bin/setenv.sh
RUN echo "CLASSPATH=/usr/local/tomcat/classpath/" >> /usr/local/tomcat/bin/setenv.sh
RUN chmod 750 /usr/local/tomcat/bin/setenv.sh

