FROM ubuntu AS build
RUN apt-get update
RUN apt-get --assume-yes  install curl
RUN mkdir maweb
WORKDIR maweb
RUN curl https://circabc.europa.eu/rest/download/11ee560a-15a2-4973-896f-cba03c70bc19?ticket= --output maweb.zip
RUN apt-get install unzip
RUN unzip maweb.zip

FROM tomcat:9-jre8-openjdk
COPY conf/fake-certificate-cert.pem /usr/local/tomcat/ssl/fake-certificate-cert.pem
COPY conf/fake-certificate-key.pem /usr/local/tomcat/ssl/fake-certificate-key.pem
COPY conf/server.xml /usr/local/tomcat/conf/server.xml
COPY --from=build maweb/app/maws.war /usr/local/tomcat/webapps/ROOT.war
COPY --from=build maweb/app/classpath /usr/local/tomcat/classpath
COPY --from=build maweb/app/libs/bcprov-jdk15on-1.68.jar /usr/local/tomcat/lib
RUN echo "# Add classpath to Tomcat CLASSPATH" > /usr/local/tomcat/bin/setenv.sh
RUN echo "CLASSPATH=/usr/local/tomcat/classpath/" >> /usr/local/tomcat/bin/setenv.sh
RUN echo "# Add paramter size" >> /usr/local/tomcat/bin/setenv.sh
RUN echo "JAVA_OPTS=-Dfile.encoding=UTF-8 -Xmx20g -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8008 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false " >> /usr/local/tomcat/bin/setenv.sh
RUN chmod 750 /usr/local/tomcat/bin/setenv.sh

